apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: llm-web-app
  namespace: ${PROJECT_ID}
  annotations:
    run.googleapis.com/ingress: all
    cloud.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 120
      serviceAccountName: llm-web-app-sa
      containers:
        - image: ${IMAGE_URI}
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 30

